## Library

In [194]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns 
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score,f1_score,precision_score,recall_score,roc_curve,roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
%matplotlib inline
# import warnings
# warnings.filterwarnings('ignore')

## The Data

In [195]:
df = pd.read_csv('diabetes2.csv')

In [196]:
df_temp = df.copy()

In [197]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [198]:
    df.shape

(768, 9)

In [199]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [201]:
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

The number of patients who has diabetes are lower than the others.

In [202]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

# Arbitrary Attribute


In [203]:
# Average Glucose for Diabetic persons
df[df.Outcome==1].Glucose.mean()

141.25746268656715

## Diabetics Prediction

In [204]:
x = df_temp.drop(['Outcome'], axis = 1)
y = df_temp.loc[:,"Outcome"].values

In [239]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 123)

In [206]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape) # instances , attributes

(537, 8)
(537,)
(231, 8)
(231,)


In [207]:
#LogisticRegression
lr = LogisticRegression(solver='liblinear', max_iter = 1000)
lr.fit(x_train, y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [208]:
lr.fit(x_train, y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [209]:
x_pred = lr.predict(x_train)

# evaluation


In [210]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, x_pred)

array([[326,  31],
       [ 94,  86]], dtype=int64)

In [211]:
#train score
score = accuracy_score(y_train, x_pred)
score

0.7672253258845437

In [212]:
y_pred = lr.predict(x_test)

In [213]:
confusion_matrix(y_pred,y_test)

array([[131,  31],
       [ 12,  57]], dtype=int64)

In [214]:
#test score 
score = accuracy_score(y_pred, y_test)
score

0.8138528138528138

In [215]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.92      0.86       143
           1       0.83      0.65      0.73        88

    accuracy                           0.81       231
   macro avg       0.82      0.78      0.79       231
weighted avg       0.82      0.81      0.81       231



## Testing Model

In [241]:
# Defined data set (it should be diabetic)
data = [[5, 10,33.7, 50, 150, 74, 0.5, 53]]

# Create the pandas DataFrame 
df_test = pd.DataFrame(data, columns = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'])

# Predict on new data
res = lr.predict(df_test)
res

array([0], dtype=int64)

Yup... The result correct